### ISSUE TITLE
Create scorekeeping visual for home page

### ISSUE THREAD

**Issue by andrew103** [Zaczero/teodle#1]
Add scorekeeping for winners of each rankdle session (if Teo wins, chat wins, or tie) and display a graphic on the home page showing the current head-to-head score.

Graphic could also be present at the end screen of a rankdle session to show the updated score immediately.

Could also enable a "History" page that shows the results of previous rankdle sessions.

**Comment by Zaczero** [comment]
I like the idea!

**Comment by Zaczero** [comment]
![image](https://user-images.githubusercontent.com/10835147/218414504-cb8c17a3-5aee-4d66-85e7-cbbfd23920ac.png)

**Comment by hddskull** [comment]
Hi, maybe you could add a column with the total amount of points. 

It would give a good idea how well Teo, chat and the leader did. It could go between "Chat" and "Leader"

**Comment by Zaczero** [comment]
If you talk about the maximum points possible, it's already done :P

![image](https://user-images.githubusercontent.com/10835147/220498299-a0999fbf-0078-4918-82d3-e024d0e4d560.png)
