### ISSUE TITLE
Clip based sort

### ISSUE THREAD

**Issue by BurningWFITA** [Zaczero/teodle#3]
I think it would be really cool to put a way to **sort the viewers by who guessed 1 or multiple clips**, like for example there has been a few moments when teo was astonished by a player's rank, it would be cool to be able to sort by the people that guessed that exact clip (clip 1, clip 2, [...], last clip would also be simpler, or maybe use a list and a list iterator to go forward and backwards, like a music player basically). Maybe you could also put the option to sort based on the fastest responses, so who had the fastest correct answer, or maybe who was the fastest overall, maybe who had the highest ratio between speed and correct guesses.
For multiple clips I mean people who guessed clip 1, and clip 5 (for example), also still considering the response time.
Then it would also be good to **put the results of Teodles into a dataframe** since you're using python but that is a plus I guess.

So far this was really great very slick and minimalistic, congrats to everybody who has been working on this

**Comment by Zaczero** [comment]
![image](https://user-images.githubusercontent.com/10835147/220498761-3bd588e7-c7c2-4dab-a818-7c6c4a4279a4.png)

When hovering over a rank you can see the TOP 5 fastest people who voted for a given rank per clip. Making anything more advanced than that, may not be that useful for the stream and it could be a little confusing (sorting by just clip 1+clip 5 for example).

However, I have another idea: https://github.com/Zaczero/teodle/issues/4. There will be a link for viewers to access the full leaderboard with all the details (CSV table perhaps). And I suppose you could perform some additional sorting there per use case.

**Comment by Zaczero** [comment]
It doesn't seem like I will be doing anything more advanced than what's been discussed above in the near future, so I will close this issue now. Thank you for the contribution! <3
