### ISSUE TITLE
Customise game

### ISSUE THREAD

**Issue by hddskull** [Zaczero/teodle#6]
Maybe you could add a settings menu where Teo could choose games from which the clips would be.

For example there 5 check boxes with csgo, valorant, overwatch, rocket league, rs6 siege. And Teo ticks only csgo, then there will be only csgo clips. 

On the index page there could be a second button called "Settings" under the "Start game" button.

**Comment by Zaczero** [comment]
Thank you for your suggestion! While the idea of allowing Teo to choose games for clips through a settings menu seems interesting, we need to consider the time constraints that Marco (the moderator) might have in picking and preparing the clips. Adding such a feature might not be the most efficient use of his time, and might not provide a significant improvement to the overall experience of the game.

Instead, I believe that a more straightforward solution would be **for Teo to communicate his preferences directly to Marco**, for example, if he wants more CS:GO clips. This way, Marco can adjust the clip selection without the need for a separate feature.
