### ISSUE TITLE
Add preview for scores per question by participants

### ISSUE THREAD

**Issue by Wouter17** [Zaczero/teodle#7]
As mentioned at [24:32] in [rankdle \#15](https://youtu.be/Nkm2tXr4bSo?t=1472): 

It would be nice to have a feature to show the past scores of players, such that it is easier for the host to see, where another player lost points.

A hover effect would probably be best suited for this.

These positions seem good for such an effect:

![example](https://user-images.githubusercontent.com/47351715/229312670-0f2afafe-ab28-4f69-8892-8fc5164feb4d.png)

**Comment by Zaczero** [comment]
Yup, I'll add that.

Oh, you have already added it, then, I'll review it :-) Thanks !
